language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

php:
    - 5.3
    - 5.4
    - 5.6
    - 7.0
    - 7.1

cache:
  directories:
    - $HOME/.composer/cache

env:
  - WP_VERSION=4.3.9 WP_MULTISITE=0
  - WP_VERSION=4.4.8 WP_MULTISITE=0
  - WP_VERSION=4.5.7 WP_MULTISITE=0
  - WP_VERSION=4.6.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0
  - WP_VERSION=4.3.9 WP_MULTISITE=1
  - WP_VERSION=4.4.8 WP_MULTISITE=1
  - WP_VERSION=4.5.7 WP_MULTISITE=1
  - WP_VERSION=4.6.4 WP_MULTISITE=1
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=nightly WP_MULTISITE=1

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

before_script:
  # Before script, failures in this section will result in build status 'failed'
before_script:
  - |
  # Remove Xdebug for a huge performance increase, but not from nightly or hhvm:
  stable='^[0-9\.]+$'
  if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
    phpenv config-rm xdebug.ini
  fi
  - phpenv config-rm xdebug.ini
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - git config --global user.email "travis-ci@codeclimate.com"
  - git config --global user.name "Travis CI"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - phpunit

after_script:
  - ./bin/codeclimate.sh

addons:
  codeclimate:
    repo_token: CODECLIMATE_REPO_TOKEN
